name: falcor_dart
description: A port of Falcor server to Dart with optional shelf middleware.
version: 0.0.1
authors:
  - Rasmus Eneman <rasmus@eneman.eu>
  - Jesper Håkansson <jesper@jesperh.se>
homepage: https://github.com/Pajn/falcor_dart

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  shelf: '^0.6.3'

dev_dependencies:
  dart_ext: "^0.0.12"
  guinness2: any
  test: any
